# Generated by Django 6.0.3 on 2026-04-27 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0019_alertefactureresolue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('attente_validation_expression', 'En attente validation expression'), ('rejetee_expression', 'Expression rejetee'), ('attente_engagement_achat', "En attente d'engagement achat"), ('attente_validation_dga_engagement', 'En attente validation DGA SOGEFI'), ('attente_validation_dg_engagement', 'En attente validation DG'), ('rejetee_dga_engagement', 'Engagement rejete par DGA SOGEFI'), ('rejetee_dg_engagement', 'Engagement rejete par DG'), ('attente_paiement_comptable', 'En attente traitement comptable SOGEFI'), ('attente_paiement_caissiere', 'En attente traitement caissiere'), ('payee', 'Payee')], default='attente_validation_expression', max_length=40)),
                ('expression_validee_le', models.DateTimeField(blank=True, null=True)),
                ('expression_validee_role', models.CharField(blank=True, max_length=40)),
                ('motif_rejet_expression', models.TextField(blank=True)),
                ('lieu_ou_projet', models.CharField(blank=True, max_length=200)),
                ('montant_engage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('engagement_observation', models.TextField(blank=True)),
                ('engagement_saisi_le', models.DateTimeField(blank=True, null=True)),
                ('validation_dga_le', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet_dga', models.TextField(blank=True)),
                ('validation_dg_le', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet_dg', models.TextField(blank=True)),
                ('mode_reglement', models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('espece', 'Espece')], max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=120)),
                ('mode_paiement_effectif', models.CharField(blank=True, max_length=100)),
                ('date_cheque', models.DateField(blank=True, null=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=80)),
                ('banque_cheque', models.CharField(blank=True, max_length=120)),
                ('beneficiaire_cheque', models.CharField(blank=True, max_length=150)),
                ('paiement_observation', models.TextField(blank=True)),
                ('paiement_saisi_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_demandees', to=settings.AUTH_USER_MODEL)),
                ('engagement_saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_engagees', to=settings.AUTH_USER_MODEL)),
                ('expression_validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_expressions_validees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='maintenance.fournisseur')),
                ('paiement_saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_payees', to=settings.AUTH_USER_MODEL)),
                ('validation_dg_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees_dg', to=settings.AUTH_USER_MODEL)),
                ('validation_dga_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees_dga', to=settings.AUTH_USER_MODEL)),
                ('type_depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='depenses.typedepense')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
