# Generated by Django 6.0.3 on 2026-04-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=180, unique=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='depense',
            name='piece_justificative',
            field=models.FileField(blank=True, upload_to='depenses/justificatifs/'),
        ),
        migrations.CreateModel(
            name='DepenseLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='depenses.depense')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='lieu_projet_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='depenses.lieuprojet'),
        ),
    ]
