# Generated by Django 6.0.3 on 2026-04-27 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_lieuprojet_depense_numero_facture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='engagement_decision_dg',
            field=models.CharField(blank=True, choices=[('validee', 'Validee'), ('rejetee', 'Rejetee')], max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='engagement_decision_dga',
            field=models.CharField(blank=True, choices=[('validee', 'Validee'), ('rejetee', 'Rejetee')], max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dg',
            field=models.CharField(blank=True, choices=[('validee', 'Validee'), ('rejetee', 'Rejetee')], max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dg_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dg_motif',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dg_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_expression_decisions_dg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dga',
            field=models.CharField(blank=True, choices=[('validee', 'Validee'), ('rejetee', 'Rejetee')], max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dga_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dga_motif',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='expression_decision_dga_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_expression_decisions_dga', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depense',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('attente_validation_expression', 'En attente validation expression DGA SOGEFI'), ('attente_validation_expression_dg', 'En attente validation expression DG'), ('rejetee_expression', 'Expression rejetee'), ('attente_engagement_achat', "En attente d'engagement achat"), ('attente_validation_dga_engagement', 'En attente validation DGA SOGEFI'), ('attente_validation_dg_engagement', 'En attente validation DG'), ('rejetee_dga_engagement', 'Engagement rejete par DGA SOGEFI'), ('rejetee_dg_engagement', 'Engagement rejete par DG'), ('attente_paiement_comptable', 'En attente traitement comptable SOGEFI'), ('attente_paiement_caissiere', 'En attente traitement caissiere'), ('payee', 'Payee')], default='attente_validation_expression', max_length=40),
        ),
    ]
