# Generated by Django 6.0.3 on 2026-04-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_depense_engagement_decision_dg_and_more'),
        ('operations', '0012_operation_latitude_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses_liees', to='operations.operation'),
        ),
        migrations.AddField(
            model_name='depense',
            name='source_depense',
            field=models.CharField(choices=[('generale', 'Depense generale'), ('chargement', 'Depense liee au chargement')], default='generale', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('attente_validation_expression', 'En attente validation expression DGA SOGEFI'), ('attente_validation_expression_dg', 'En attente validation expression DG'), ('rejetee_expression', 'Expression rejetee'), ('attente_validation_chargement_dga', 'En attente validation depense chargement DGA SOGEFI'), ('attente_validation_chargement_dg', 'En attente validation depense chargement DG'), ('rejetee_chargement', 'Depense de chargement rejetee'), ('attente_engagement_achat', "En attente d'engagement achat"), ('attente_validation_dga_engagement', 'En attente validation DGA SOGEFI'), ('attente_validation_dg_engagement', 'En attente validation DG'), ('rejetee_dga_engagement', 'Engagement rejete par DGA SOGEFI'), ('rejetee_dg_engagement', 'Engagement rejete par DG'), ('attente_paiement_comptable', 'En attente traitement comptable SOGEFI'), ('attente_paiement_caissiere', 'En attente traitement caissiere'), ('payee', 'Payee')], default='attente_validation_expression', max_length=40),
        ),
    ]
