# Generated by Django 6.0.3 on 2026-04-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0004_depense_operation_depense_source_depense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='libelle_depense',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
