# Generated by Django 6.0.3 on 2026-04-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0005_depense_libelle_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedepense',
            name='montant_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
