# Generated by Django 6.0.3 on 2026-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0006_typedepense_montant_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='receveur_fonction',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='depense',
            name='receveur_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='depense',
            name='receveur_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='depense',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('attente_validation_expression', 'En attente validation expression DGA SOGEFI'), ('attente_validation_expression_dg', 'En attente validation expression DG'), ('rejetee_expression', 'Expression rejetee'), ('attente_validation_chargement_dga', 'En attente validation depense chargement DGA'), ('attente_validation_chargement_dg', 'En attente validation depense chargement DG'), ('rejetee_chargement', 'Depense de chargement rejetee'), ('attente_engagement_achat', "En attente d'engagement achat"), ('attente_validation_dga_engagement', 'En attente validation DGA SOGEFI'), ('attente_validation_dg_engagement', 'En attente validation DG'), ('rejetee_dga_engagement', 'Engagement rejete par DGA SOGEFI'), ('rejetee_dg_engagement', 'Engagement rejete par DG'), ('attente_paiement_comptable', 'En attente traitement comptable SOGEFI'), ('attente_paiement_caissiere', 'En attente traitement caissiere'), ('payee', 'Payee')], default='attente_validation_expression', max_length=40),
        ),
    ]
