# Generated by Django 6.0.3 on 2026-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0007_depense_receveur_fonction_depense_receveur_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='date_bon_conso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='quantite_a_consommer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
