# Generated by Django 6.0.3 on 2026-05-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_commande_delai_paiement_jours_and_more'),
        ('depenses', '0009_depenseligne_type_depense_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_liees', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='depense',
            name='portee_chargement',
            field=models.CharField(choices=[('bl', 'BL uniquement'), ('commande', 'Commande entiere')], default='bl', max_length=20),
        ),
    ]
