# Generated by Django 6.0.3 on 2026-05-19 23:11

import django.db.models.deletion
from django.db import migrations, models


def seed_default_type_pieces(apps, schema_editor):
    TypePieceIdentite = apps.get_model('depenses', 'TypePieceIdentite')
    for libelle in ["Carte d'identite", "Passport", "Autre"]:
        TypePieceIdentite.objects.get_or_create(libelle=libelle)


def unseed_default_type_pieces(apps, schema_editor):
    TypePieceIdentite = apps.get_model('depenses', 'TypePieceIdentite')
    TypePieceIdentite.objects.filter(libelle__in=["Carte d'identite", "Passport", "Autre"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0010_depense_commande_depense_portee_chargement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePieceIdentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='depense',
            name='type_piece_identite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='depenses.typepieceidentite'),
        ),
        migrations.RunPython(seed_default_type_pieces, unseed_default_type_pieces),
    ]
