# Generated by Django 6.0.3 on 2026-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0016_internal_reference_entities'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='typedepense',
            name='unique_type_depense_par_portefeuille',
        ),
        migrations.AlterField(
            model_name='lieuprojet',
            name='libelle',
            field=models.CharField(max_length=180),
        ),
        migrations.AddConstraint(
            model_name='lieuprojet',
            constraint=models.UniqueConstraint(fields=('libelle', 'entite_reference'), name='unique_lieu_projet_par_entite'),
        ),
        migrations.AddConstraint(
            model_name='typedepense',
            constraint=models.UniqueConstraint(fields=('libelle', 'portefeuille', 'entite_reference'), name='unique_type_depense_par_portefeuille_entite'),
        ),
    ]
