# Generated by Django 6.0.3 on 2026-05-23 17:45

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_justificatifs(apps, schema_editor):
    Depense = apps.get_model("depenses", "Depense")
    DepenseJustificatif = apps.get_model("depenses", "DepenseJustificatif")

    for depense in Depense.objects.exclude(piece_justificative=""):
        already_exists = DepenseJustificatif.objects.filter(
            depense_id=depense.id,
            fichier=depense.piece_justificative,
        ).exists()
        if not already_exists:
            DepenseJustificatif.objects.create(
                depense_id=depense.id,
                fichier=depense.piece_justificative,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0017_remove_typedepense_unique_type_depense_par_portefeuille_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseJustificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='depenses/justificatifs/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='depenses.depense')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(migrate_existing_justificatifs, migrations.RunPython.noop),
    ]
