# Generated by Django 6.0.3 on 2026-04-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('date_livraison_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='nouvelle', max_length=20)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
