# Generated by Django 6.0.3 on 2026-04-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('operations', '0003_alter_operation_etat_bon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='montant',
            new_name='quantite',
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='operations.produit'),
        ),
    ]
