# Generated by Django 6.0.3 on 2026-04-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_remove_commande_montant_commande_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_validation_dg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_negocie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('attente_validation_dg', 'En attente validation DG'), ('validee_dg', 'Validee par DG'), ('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='attente_validation_dg', max_length=30),
        ),
    ]
