# Generated by Django 6.0.3 on 2026-04-23 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_date_validation_dg_commande_prix_negocie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
