# Generated by Django 6.0.3 on 2026-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('attente_validation_dg', 'En attente validation DG'), ('validee_dg', 'Validee par DG'), ('rejetee_dg', 'Rejetee par DG'), ('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='attente_validation_dg', max_length=30),
        ),
    ]
