# Generated by Django 6.0.3 on 2026-04-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0008_camion_code_camion'),
        ('chauffeurs', '0002_chauffeur_camion'),
        ('commandes', '0005_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='camions.camion'),
        ),
        migrations.AddField(
            model_name='commande',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='chauffeurs.chauffeur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_affectation_logistique',
            field=models.DateField(blank=True, null=True),
        ),
    ]
