# Generated by Django 6.0.3 on 2026-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_commande_camion_commande_chauffeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_validation_dga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='decision_dg',
            field=models.CharField(blank=True, choices=[('validee', 'Validee'), ('rejetee', 'Rejetee')], max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='decision_dga',
            field=models.CharField(blank=True, choices=[('validee', 'Validee'), ('rejetee', 'Rejetee')], max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_rejet_dg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_rejet_dga',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='observation_dg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='observation_dga',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('attente_validation_dga', 'En attente validation DGA'), ('attente_validation_dg', 'En attente validation DG'), ('validee_dg', 'Validee par DG'), ('rejetee_dg', 'Rejetee par DG'), ('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='attente_validation_dg', max_length=30),
        ),
    ]
