# Generated by Django 6.0.3 on 2026-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_commande_date_validation_dga_commande_decision_dg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delai_paiement_jours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
