# Generated by Django 6.0.3 on 2026-05-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_villeperequation_and_more'),
        ('commandes', '0009_alter_commande_reference_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='tarif_perequation_gnf_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='ville_perequation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.villeperequation'),
        ),
    ]
