# Generated by Django 6.0.3 on 2026-04-13 20:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('entreprise'), name='unique_prospect_entreprise_ci'),
        ),
    ]
