# Generated by Django 6.0.3 on 2026-04-26 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_prospect_unique_prospect_entreprise_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portefeuille_prospects', to=settings.AUTH_USER_MODEL),
        ),
    ]
