# Generated by Django 6.0.3 on 2026-04-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_prospect_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='fonction',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
