# Generated by Django 6.0.3 on 2026-03-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0001_initial'),
        ('chauffeurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camions.camion'),
        ),
    ]
