from django.urls import path

from . import views


urlpatterns = [
    path("", views.liste_operations, name="operations"),
    path("export/xls/", views.export_operations_xls, name="export_operations_xls"),
    path("export/pdf/", views.export_operations_pdf, name="export_operations_pdf"),
    path("ajouter/", views.ajouter_operation, name="ajouter_operation"),
    path("modifier/<int:id>/", views.modifier_operation, name="modifier_operation"),
    path("supprimer/<int:id>/", views.supprimer_operation, name="supprimer_operation"),
    path("comptable/", views.comptable_operations, name="comptable_operations"),
    path("secretaire/", views.secretaire_operations, name="secretaire_operations"),
    path("secretaire/export/xls/", views.export_secretaire_xls, name="export_secretaire_xls"),
    path("secretaire/export/pdf/", views.export_secretaire_pdf, name="export_secretaire_pdf"),
    path("secretaire/transmission/", views.transmettre_bons_secretaire, name="transmettre_bons_secretaire"),
    path("comptable/sommiers/", views.sommiers_operations, name="sommiers_operations"),
    path("comptable/ajouter/", views.ajouter_operation_comptable, name="ajouter_operation_comptable"),
    path("comptable/<int:id>/modifier/", views.modifier_operation_comptable, name="modifier_operation_comptable"),
    path("comptable/<int:id>/supprimer/", views.supprimer_operation_comptable, name="supprimer_operation_comptable"),
    path("comptable/<int:id>/bon-livraison/", views.imprimer_bon_livraison, name="imprimer_bon_livraison"),
    path("facturation/", views.facturation_operations, name="facturation_operations"),
    path("facturation/<int:id>/modifier/", views.modifier_operation_facturation, name="modifier_operation_facturation"),
    path("facturation/<int:id>/sans-tva/", views.imprimer_facture_sans_tva, name="imprimer_facture_sans_tva"),
    path("facturation/<int:id>/avec-tva/", views.imprimer_facture_avec_tva, name="imprimer_facture_avec_tva"),
    path("facturation/<int:id>/sans-tva-manquant/", views.imprimer_facture_sans_tva_manquant, name="imprimer_facture_sans_tva_manquant"),
    path("facturation/<int:id>/avec-tva-manquant/", views.imprimer_facture_avec_tva_manquant, name="imprimer_facture_avec_tva_manquant"),
    path("logistique/", views.logistique_operations, name="logistique_operations"),
    path("logistique/reception/", views.valider_receptions_logistiques, name="valider_receptions_logistiques"),
    path("logistique/<int:id>/modifier/", views.modifier_operation_logistique, name="modifier_operation_logistique"),
    path("logistique/historique/<int:id>/", views.ancienne_fiche_operation_logistique, name="ancienne_fiche_operation_logistique"),
    path("transitaire/", views.transitaire_operations, name="transitaire_operations"),
    path("transitaire/export/xls/", views.export_transitaire_xls, name="export_transitaire_xls"),
    path("transitaire/export/pdf/", views.export_transitaire_pdf, name="export_transitaire_pdf"),
    path("transitaire/historique/", views.historique_transitaire_operations, name="historique_transitaire_operations"),
    path("transitaire/historique/export/xls/", views.export_transitaire_historique_xls, name="export_transitaire_historique_xls"),
    path("transitaire/historique/export/pdf/", views.export_transitaire_historique_pdf, name="export_transitaire_historique_pdf"),
    path("transitaire/reception/", views.valider_reception_transitaire, name="valider_reception_transitaire"),
    path("transitaire/action-groupee/<str:action_name>/", views.action_groupee_transitaire, name="action_groupee_transitaire"),
    path("transitaire/<int:id>/transferer-logistique/", views.transferer_liquide_logistique, name="transferer_liquide_logistique"),
    path("transitaire/<int:id>/charger-direct/", views.charger_bon_direct, name="charger_bon_direct"),
    path("transitaire/<int:id>/<str:etat>/", views.changer_etat_transitaire, name="changer_etat_transitaire"),
    path("logisticien/", views.logisticien_operations, name="logisticien_operations"),
    path("logisticien/export/xls/", views.export_logisticien_xls, name="export_logisticien_xls"),
    path("logisticien/export/pdf/", views.export_logisticien_pdf, name="export_logisticien_pdf"),
    path("logisticien/<int:id>/modifier/", views.modifier_operation_logisticien, name="modifier_operation_logisticien"),
    path("chef-chauffeur/", views.chef_chauffeur_operations, name="chef_chauffeur_operations"),
    path("chef-chauffeur/historique/", views.historique_chef_chauffeur_operations, name="historique_chef_chauffeur_operations"),
    path("chef-chauffeur/<int:id>/action/<str:action>/", views.action_chef_chauffeur, name="action_chef_chauffeur"),
    path("chef-chauffeur/<int:id>/modifier/", views.modifier_operation_logisticien, name="modifier_operation_chef_chauffeur"),
    path("produits/", views.gestion_produits, name="gestion_produits"),
    path("produits/ajouter-modal/", views.ajouter_produit_modal, name="ajouter_produit_modal"),
    path("regimes/ajouter-modal/", views.ajouter_regime_modal, name="ajouter_regime_modal"),
    path("depots/ajouter-modal/", views.ajouter_depot_modal, name="ajouter_depot_modal"),
    path("chauffeur-par-camion/", views.chauffeur_par_camion, name="chauffeur_par_camion"),
    path("commande-infos/", views.commande_infos, name="commande_infos"),
]
