# Generated by Django 6.0.3 on 2026-03-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='entreprise',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
