# Generated by Django 6.0.3 on 2026-04-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_entreprise'),
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_convertis', to='prospects.prospect'),
        ),
    ]
