# Generated by Django 6.0.3 on 2026-04-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fonction_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ClientDestinationAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='clients.client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
