# Generated by Django 6.0.3 on 2026-04-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_fonction_contact_clientdestinationadresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_solde_initial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='decouvert_maximum_autorise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='client',
            name='delai_paiement_jours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='solde_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
