# Generated by Django 6.0.3 on 2026-04-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_date_solde_initial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncaissementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_encaissement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement'), ('cheque', 'Cheque'), ('espece', 'Espece'), ('mobile_money', 'Mobile money')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('observation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='clients.client')),
            ],
            options={
                'ordering': ['-date_encaissement', '-id'],
            },
        ),
    ]
