# Generated by Django 6.0.3 on 2026-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_encaissementclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaissementclient',
            name='banque',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='encaissementclient',
            name='fonction_deposant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='encaissementclient',
            name='nom_deposant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='encaissementclient',
            name='numero_deposant',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
