# Generated by Django 6.0.3 on 2026-04-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_encaissementclient_banque_and_more'),
        ('commandes', '0008_commande_delai_paiement_jours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaissementclient',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissements_clients', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='encaissementclient',
            name='type_encaissement',
            field=models.CharField(choices=[('commande', 'Paiement sur commande'), ('solde_initial', 'Paiement sur solde initial')], default='commande', max_length=20),
        ),
    ]
