# Generated by Django 6.0.3 on 2026-05-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_encaissementclient_commande_and_more'),
        ('commandes', '0008_commande_delai_paiement_jours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='encaissementclient',
            name='type_encaissement',
            field=models.CharField(choices=[('commande', 'Paiement sur commande'), ('multi_commandes', 'Paiement reparti sur plusieurs commandes'), ('avance_client', 'Avance client'), ('solde_initial', 'Paiement sur solde initial')], default='commande', max_length=20),
        ),
        migrations.CreateModel(
            name='EncaissementClientAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_affecte', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissement_allocations', to='commandes.commande')),
                ('encaissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='clients.encaissementclient')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('encaissement', 'commande')},
            },
        ),
    ]
