# Generated by Django 6.0.3 on 2026-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_encaissementclientallocation_cible_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_entreprise',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='gerant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_entreprise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='rccm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
