# Generated by Django 6.0.3 on 2026-05-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_email_entreprise_client_gerant_client_nif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillePerequation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('tarif_gnf_litre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='clientdestinationadresse',
            name='ville_perequation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinations_clients', to='clients.villeperequation'),
        ),
    ]
