# Generated by Django 6.0.3 on 2026-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_profilutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='disabled_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
