# Generated by Django 6.0.3 on 2026-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_profilutilisateur_disabled_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='enabled_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
