# Generated by Django 6.0.3 on 2026-04-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('assurance', 'Assurance'), ('carte_grise', 'Carte grise'), ('visite_technique', 'Visite technique'), ('taxe', 'Taxe / vignette'), ('autre', 'Autre')], max_length=30)),
                ('numero_document', models.CharField(max_length=100)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='camions.camion')),
            ],
            options={
                'ordering': ['date_expiration', '-date_creation'],
            },
        ),
    ]
