# Generated by Django 6.0.3 on 2026-04-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camions', '0001_initial'),
        ('chauffeurs', '0002_chauffeur_camion'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='planifiee', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='camions.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='chauffeurs.chauffeur')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
