# Generated by Django 6.0.3 on 2026-04-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Revision generale'), ('panne', 'Reparation de panne'), ('pneus', 'Changement de pneus'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee')], default='planifiee', max_length=20)),
                ('prestataire', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='camions.camion')),
            ],
            options={
                'ordering': ['-date_debut', '-date_creation'],
            },
        ),
    ]
