# Generated by Django 6.0.3 on 2026-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_maintenance_statut_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminee'), ('refusee', 'Refusee'), ('annulee', 'Annulee')], default='en_cours', max_length=20),
        ),
    ]
