# Generated by Django 6.0.3 on 2026-04-15 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_maintenance_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=150)),
                ('entreprise', models.CharField(max_length=150)),
                ('domaine_activite', models.CharField(blank=True, max_length=150)),
                ('numero_telephone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['nom_fournisseur', 'entreprise'],
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='validation_dg_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='validation_dg_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_dg_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='validation_dga_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='validation_dga_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_dga_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='validation_logistique_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='validation_logistique_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logistique_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='maintenance.fournisseur'),
        ),
    ]
