# Generated by Django 6.0.3 on 2026-04-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_fournisseur_maintenance_date_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prestataire', models.CharField(max_length=150)),
                ('entreprise', models.CharField(blank=True, max_length=150)),
                ('domaine_activite', models.CharField(blank=True, max_length=150)),
                ('numero_telephone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['nom_prestataire', 'entreprise'],
            },
        ),
    ]
