# Generated by Django 6.0.3 on 2026-04-16 10:09

import unicodedata

from django.db import migrations, models


def dedupe_fournisseurs(apps, schema_editor):
    Fournisseur = apps.get_model("maintenance", "Fournisseur")
    Maintenance = apps.get_model("maintenance", "Maintenance")

    def normalize_text(value):
        value = (value or "").strip()
        if not value:
            return ""
        value = unicodedata.normalize("NFKD", value)
        value = "".join(char for char in value if not unicodedata.combining(char))
        return " ".join(value.lower().split())

    def merge_into(primary, duplicates):
        updated_fields = []
        if not primary.numero_telephone:
            phone = next((item.numero_telephone for item in duplicates if item.numero_telephone), None)
            if phone:
                primary.numero_telephone = phone
                updated_fields.append("numero_telephone")
        if not primary.entreprise:
            entreprise = next((item.entreprise for item in duplicates if item.entreprise), "")
            if entreprise:
                primary.entreprise = entreprise
                updated_fields.append("entreprise")
        if not primary.domaine_activite:
            domaine = next((item.domaine_activite for item in duplicates if item.domaine_activite), "")
            if domaine:
                primary.domaine_activite = domaine
                updated_fields.append("domaine_activite")
        if updated_fields:
            primary.save(update_fields=updated_fields)

        duplicate_ids = [item.id for item in duplicates]
        if duplicate_ids:
            Maintenance.objects.filter(fournisseur_id__in=duplicate_ids).update(fournisseur_id=primary.id)
            Fournisseur.objects.filter(id__in=duplicate_ids).delete()

    # Normalize phone values before enforcing uniqueness.
    for fournisseur in Fournisseur.objects.all().order_by("id"):
        normalized_phone = (fournisseur.numero_telephone or "").strip() or None
        if fournisseur.numero_telephone != normalized_phone:
            fournisseur.numero_telephone = normalized_phone
            fournisseur.save(update_fields=["numero_telephone"])

    # Merge duplicates that share the same normalized supplier identity.
    seen_by_identity = {}
    for fournisseur in Fournisseur.objects.all().order_by("id"):
        identity = (
            normalize_text(fournisseur.nom_fournisseur),
            normalize_text(fournisseur.entreprise),
        )
        if not identity[0]:
            continue
        if identity not in seen_by_identity:
            seen_by_identity[identity] = fournisseur
            continue
        merge_into(seen_by_identity[identity], [fournisseur])

    # Merge duplicates that share the same phone number.
    seen_by_phone = {}
    for fournisseur in Fournisseur.objects.exclude(numero_telephone__isnull=True).order_by("id"):
        phone = normalize_text(fournisseur.numero_telephone)
        if not phone:
            continue
        if phone not in seen_by_phone:
            seen_by_phone[phone] = fournisseur
            continue
        merge_into(seen_by_phone[phone], [fournisseur])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('maintenance', '0011_prestataire'),
    ]

    operations = [
        migrations.RunPython(dedupe_fournisseurs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fournisseur',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
