# Generated by Django 6.0.3 on 2026-04-16 10:09

from django.db import migrations, models


def dedupe_fournisseurs(apps, schema_editor):
    Fournisseur = apps.get_model("maintenance", "Fournisseur")
    Maintenance = apps.get_model("maintenance", "Maintenance")

    def merge_into(primary, duplicates):
        updated_fields = []
        if not primary.numero_telephone:
            phone = next((item.numero_telephone for item in duplicates if item.numero_telephone), None)
            if phone:
                primary.numero_telephone = phone
                updated_fields.append("numero_telephone")
        if not primary.entreprise:
            entreprise = next((item.entreprise for item in duplicates if item.entreprise), "")
            if entreprise:
                primary.entreprise = entreprise
                updated_fields.append("entreprise")
        if not primary.domaine_activite:
            domaine = next((item.domaine_activite for item in duplicates if item.domaine_activite), "")
            if domaine:
                primary.domaine_activite = domaine
                updated_fields.append("domaine_activite")
        if updated_fields:
            primary.save(update_fields=updated_fields)

        duplicate_ids = [item.id for item in duplicates]
        if duplicate_ids:
            Maintenance.objects.filter(fournisseur_id__in=duplicate_ids).update(fournisseur_id=primary.id)
            Fournisseur.objects.filter(id__in=duplicate_ids).delete()

    # Normalise blank phone values to NULL before uniqueness.
    Fournisseur.objects.filter(numero_telephone="").update(numero_telephone=None)

    # Keep a single Ousmane Kante record if duplicates exist.
    ousmane_entries = list(Fournisseur.objects.filter(nom_fournisseur__iexact="ousmane kante").order_by("id"))
    if len(ousmane_entries) > 1:
        primary = ousmane_entries[0]
        merge_into(primary, ousmane_entries[1:])

    # Merge duplicates that share the same phone number.
    seen_by_phone = {}
    for fournisseur in Fournisseur.objects.exclude(numero_telephone__isnull=True).order_by("id"):
        phone = (fournisseur.numero_telephone or "").strip()
        if not phone:
            continue
        if phone not in seen_by_phone:
            seen_by_phone[phone] = fournisseur
            continue
        merge_into(seen_by_phone[phone], [fournisseur])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_prestataire'),
    ]

    operations = [
        migrations.RunPython(dedupe_fournisseurs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fournisseur',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
