# Generated by Django 6.0.3 on 2026-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_alter_fournisseur_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
