# Generated by Django 6.0.3 on 2026-04-16 15:22

from django.db import migrations, models


def remap_maintenance_statuses(apps, schema_editor):
    Maintenance = apps.get_model("maintenance", "Maintenance")

    for maintenance in Maintenance.objects.all():
        current = maintenance.statut
        if current == "refusee":
            maintenance.statut = "rejetee_dga"
        elif current == "annulee":
            maintenance.statut = "rejetee_dg"
        elif current == "terminee":
            maintenance.statut = "payee" if maintenance.date_paiement else "attente_paiement"
        elif current == "en_cours":
            if maintenance.validation_dg_at:
                maintenance.statut = "payee" if maintenance.date_paiement else "attente_paiement"
            elif maintenance.validation_dga_at:
                maintenance.statut = "attente_dg"
            elif maintenance.validation_logistique_at:
                maintenance.statut = "attente_dga"
            else:
                maintenance.statut = "en_cours"
        else:
            continue
        maintenance.save(update_fields=["statut"])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_fournisseur_email_fournisseur_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(remap_maintenance_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'Diagnostic en cours'), ('attente_prix', 'En attente de saisie de prix'), ('attente_dga', 'En attente validation DGA'), ('attente_dg', 'En attente validation DG'), ('attente_paiement', 'En attente de paiement'), ('payee', 'Payee'), ('rejetee_dga', 'Rejetee par le DGA'), ('rejetee_dg', 'Rejetee par le DG')], default='en_cours', max_length=30),
        ),
    ]
