# Generated by Django 6.0.3 on 2026-04-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_articlestock_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancesousligne',
            name='article_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_consommees', to='maintenance.articlestock'),
        ),
        migrations.AddField(
            model_name='maintenancesousligne',
            name='mouvement_stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_maintenance', to='maintenance.mouvementstock'),
        ),
    ]
