# Generated by Django 6.0.3 on 2026-04-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_maintenancesousligne_article_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='coefficient_conversion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='quantite_saisie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='unite_saisie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ArticleStockConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_source', models.CharField(max_length=50)),
                ('quantite_equivalente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='maintenance.articlestock')),
            ],
            options={
                'ordering': ['-quantite_equivalente', 'unite_source'],
                'constraints': [models.UniqueConstraint(fields=('article', 'unite_source'), name='unique_conversion_unit_by_article')],
            },
        ),
    ]
