# Generated by Django 6.0.3 on 2026-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_mouvementstock_coefficient_conversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='facture_fichier',
            field=models.FileField(blank=True, upload_to='maintenance/factures/'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'Diagnostic en cours'), ('attente_prix', 'En attente de saisie de prix'), ('attente_dga', 'En attente validation DGA'), ('attente_dg', 'En attente validation DG'), ('attente_paiement', 'En attente de paiement'), ('payee', 'Payee'), ('validee_stock', 'Validee stock'), ('rejetee_dga', 'Rejetee par le DGA'), ('rejetee_dg', 'Rejetee par le DG')], default='en_cours', max_length=30),
        ),
    ]
