# Generated by Django 6.0.3 on 2026-05-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_mouvementstock_fournisseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanneCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=160)),
                ('type_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes_catalogue', to='maintenance.typemaintenance')),
            ],
            options={
                'ordering': ['type_maintenance__libelle', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='maintenancesousligne',
            name='panne_catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_lignes_maintenance', to='maintenance.pannecatalogue'),
        ),
        migrations.AddConstraint(
            model_name='pannecatalogue',
            constraint=models.UniqueConstraint(fields=('type_maintenance', 'libelle'), name='unique_panne_by_type_maintenance'),
        ),
    ]
