# Generated by Django 6.0.3 on 2026-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_pannecatalogue_maintenancesousligne_panne_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='receveur_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='receveur_poste',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='receveur_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
