# Generated by Django 6.0.3 on 2026-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_maintenance_receveur_nom_maintenance_receveur_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestock',
            name='prix_conditionnement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='articlestock',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='prix_conditionnement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
