# Generated by Django 6.0.3 on 2026-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_alter_articlestock_prix_conditionnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestock',
            name='prix_conditionnement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='articlestock',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='montant_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='prix_conditionnement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
