# Generated by Django 6.0.3 on 2026-05-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_alter_articlestock_prix_conditionnement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=80)),
                ('facture_fichier', models.FileField(upload_to='maintenance/factures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_maintenance', to='maintenance.fournisseur')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_achat', to='maintenance.maintenance')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
