# Generated by Django 6.0.3 on 2026-05-19 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0011_typepieceidentite_depense_numero_piece_identite_and_more'),
        ('maintenance', '0030_soldeinitialcaisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='banque_cheque',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='beneficiaire_cheque',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_cheque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='reference_cheque',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_piece_identite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='depenses.typepieceidentite'),
        ),
        migrations.AlterField(
            model_name='approvisionnementcaisse',
            name='nature_approvisionnement',
            field=models.CharField(choices=[('urgence_dg_espece', 'Avance DG en espece'), ('retrait_remboursement', 'Remboursement DG par cheque'), ('cheque_direct', 'Approvisionnement caisse par cheque')], default='urgence_dg_espece', max_length=40),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('espece', 'Espece')], max_length=20),
        ),
    ]
