# Generated by Django 6.0.3 on 2026-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0034_fournisseur_entite_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnementcaisse',
            name='nature_approvisionnement',
            field=models.CharField(choices=[('urgence_dg_espece', 'Emprunt DG en espece'), ('remboursement_dg_espece', 'Remboursement DG en espece'), ('retour_caisse', 'Retour en caisse'), ('retrait_remboursement', 'Remboursement DG par cheque'), ('cheque_direct', 'Approvisionnement caisse par cheque')], default='urgence_dg_espece', max_length=40),
        ),
    ]
