# Generated by Django 6.0.3 on 2026-06-02 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0035_alter_approvisionnementcaisse_nature_approvisionnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanneFournisseurPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('observation', models.CharField(blank=True, max_length=180)),
                ('date_reference', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_pannes', to='maintenance.fournisseur')),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_fournisseurs', to='maintenance.pannecatalogue')),
            ],
            options={
                'ordering': ['-date_reference', 'fournisseur__nom_fournisseur'],
                'constraints': [models.UniqueConstraint(fields=('panne', 'fournisseur'), name='unique_prix_panne_fournisseur')],
            },
        ),
    ]
