# Generated by Django 6.0.3 on 2026-04-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camions', '0001_initial'),
        ('chauffeurs', '0002_chauffeur_camion'),
        ('clients', '0002_alter_client_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bl', models.CharField(max_length=50, unique=True)),
                ('etat_bon', models.CharField(choices=[('brouillon', 'Brouillon'), ('transmis', 'Transmis'), ('charge', 'Charge'), ('livre', 'Livre'), ('retour_bureau', 'Retour bureau'), ('liquide', 'Liquide')], default='brouillon', max_length=30)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_bl', models.DateField(blank=True, null=True)),
                ('date_transmission', models.DateField(blank=True, null=True)),
                ('date_bons_liquides', models.DateField(blank=True, null=True)),
                ('date_bons_charges', models.DateField(blank=True, null=True)),
                ('date_bons_livres', models.DateField(blank=True, null=True)),
                ('date_bon_retour', models.DateField(blank=True, null=True)),
                ('date_decharge_chauffeur', models.DateField(blank=True, null=True)),
                ('heure_decharge_chauffeur', models.TimeField(blank=True, null=True)),
                ('livreur', models.CharField(blank=True, max_length=150)),
                ('observation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='camions.camion')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='chauffeurs.chauffeur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='clients.client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='operations.destination')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.produit')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
