# Generated by Django 6.0.3 on 2026-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
