# Generated by Django 6.0.3 on 2026-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_operation_destination_delete_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='etat_bon',
            field=models.CharField(choices=[('initie', 'Initie'), ('declare', 'Declare'), ('charge', 'Charge'), ('livre', 'Livre'), ('liquide', 'Liquide')], default='initie', max_length=30),
        ),
    ]
