# Generated by Django 6.0.3 on 2026-04-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0001_initial'),
        ('chauffeurs', '0002_chauffeur_camion'),
        ('commandes', '0002_remove_commande_montant_commande_produit_and_more'),
        ('operations', '0003_alter_operation_etat_bon'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='operation',
            name='date_facture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='montant_facture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='operation',
            name='camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='camions.camion'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='chauffeurs.chauffeur'),
        ),
    ]
