# Generated by Django 6.0.3 on 2026-04-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_operation_commande_operation_date_facture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RegimeDouanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True)),
                ('code_regime', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.depot'),
        ),
        migrations.AddField(
            model_name='operation',
            name='regime_douanier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.regimedouanier'),
        ),
    ]
