# Generated by Django 6.0.3 on 2026-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_depot_regimedouanier_operation_reference_externe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='etat_bon',
            field=models.CharField(choices=[('initie', 'Initie'), ('declare', 'Declare'), ('liquide', 'Liquide'), ('charge', 'Charge'), ('livre', 'Livre')], default='initie', max_length=30),
        ),
    ]
