# Generated by Django 6.0.3 on 2026-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_operation_etat_bon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='montant_facture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
