# Generated by Django 6.0.3 on 2026-04-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0008_camion_code_camion'),
        ('chauffeurs', '0002_chauffeur_camion'),
        ('operations', '0007_alter_operation_montant_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAffectationOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_livreur', models.CharField(blank=True, max_length=150)),
                ('ancienne_date_decharge_chauffeur', models.DateField(blank=True, null=True)),
                ('ancienne_heure_decharge_chauffeur', models.TimeField(blank=True, null=True)),
                ('ancien_etat_bon', models.CharField(blank=True, choices=[('initie', 'Initie'), ('declare', 'Declare'), ('liquide', 'Liquide'), ('charge', 'Charge'), ('livre', 'Livre')], max_length=30)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('ancien_camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_affectation_operation', to='camions.camion')),
                ('ancien_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_affectation_operation', to='chauffeurs.chauffeur')),
                ('nouveau_camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouveaux_historiques_affectation_operation', to='camions.camion')),
                ('nouveau_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouveaux_historiques_affectation_operation', to='chauffeurs.chauffeur')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_affectation', to='operations.operation')),
            ],
            options={
                'ordering': ['-date_changement'],
            },
        ),
    ]
