# Generated by Django 6.0.3 on 2026-04-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_historiqueaffectationoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='remplace_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_versions', to='operations.operation'),
        ),
    ]
