# Generated by Django 6.0.3 on 2026-04-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_operation_remplace_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sommier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sm', models.CharField(max_length=50, unique=True)),
                ('date_sommier', models.DateField()),
                ('reference_navire', models.CharField(max_length=150)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_disponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sommiers', to='operations.produit')),
            ],
            options={
                'ordering': ['-date_sommier', 'numero_sm'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='sommier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.sommier'),
        ),
    ]
