# Generated by Django 6.0.3 on 2026-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_sommier_operation_sommier'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='stock_sommier_deduit',
            field=models.BooleanField(default=False),
        ),
    ]
