# Generated by Django 6.0.3 on 2026-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_operation_stock_sommier_deduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='latitude_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='longitude_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='mouvement_camion',
            field=models.TextField(blank=True),
        ),
    ]
