# Generated by Django 6.0.3 on 2026-04-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_operation_latitude_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='quantite_livree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
