# Generated by Django 6.0.3 on 2026-04-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_rename_date_transmission_operation_date_transmission_depot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date_reception_logistique',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='date_reception_transitaire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='date_remise_chauffeur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='date_transfert_logistique',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='remis_a_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='operation',
            name='remis_a_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historiqueaffectationoperation',
            name='ancien_etat_bon',
            field=models.CharField(blank=True, choices=[('initie', 'Initie'), ('attente_reception_transitaire', 'En attente validation reception transitaire'), ('transmis', 'Transmis'), ('declare', 'Declare'), ('liquide', 'Liquide'), ('attente_reception_logistique', 'Liquides en attente validation reception logistique'), ('liquide_logistique', 'BL liquides logistique'), ('liquide_chauffeur', 'BL liquide chauffeur'), ('charge', 'Charge'), ('livre', 'Livre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='operation',
            name='etat_bon',
            field=models.CharField(choices=[('initie', 'Initie'), ('attente_reception_transitaire', 'En attente validation reception transitaire'), ('transmis', 'Transmis'), ('declare', 'Declare'), ('liquide', 'Liquide'), ('attente_reception_logistique', 'Liquides en attente validation reception logistique'), ('liquide_logistique', 'BL liquides logistique'), ('liquide_chauffeur', 'BL liquide chauffeur'), ('charge', 'Charge'), ('livre', 'Livre')], default='initie', max_length=30),
        ),
    ]
