# Generated by Django 6.0.3 on 2026-05-25 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0009_camion_est_affrete_transporteur_telephone'),
        ('chauffeurs', '0002_chauffeur_camion'),
        ('commandes', '0010_commande_tarif_perequation_gnf_litre_and_more'),
        ('operations', '0015_operation_date_reception_logistique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueaffectationoperation',
            name='ancien_etat_bon',
            field=models.CharField(blank=True, choices=[('initie', 'Initie'), ('attente_reception_transitaire', 'BL secretaire'), ('transmis', 'Transmis'), ('declare', 'Declare'), ('liquide', 'Liquide'), ('attente_reception_logistique', 'Liquides en attente validation reception logistique'), ('liquide_logistique', 'BL liquides logistique'), ('liquide_chauffeur', 'BL liquide chauffeur'), ('charge', 'Charge'), ('livre', 'Livre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='operation',
            name='etat_bon',
            field=models.CharField(choices=[('initie', 'Initie'), ('attente_reception_transitaire', 'BL secretaire'), ('transmis', 'Transmis'), ('declare', 'Declare'), ('liquide', 'Liquide'), ('attente_reception_logistique', 'Liquides en attente validation reception logistique'), ('liquide_logistique', 'BL liquides logistique'), ('liquide_chauffeur', 'BL liquide chauffeur'), ('charge', 'Charge'), ('livre', 'Livre')], default='initie', max_length=30),
        ),
        migrations.CreateModel(
            name='DemandeNouveauBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitee'), ('annulee', 'Annulee')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ancienne_operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_nouveau_bl', to='operations.operation')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_nouveau_bl', to='commandes.commande')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_nouveau_bl_creees', to=settings.AUTH_USER_MODEL)),
                ('nouveau_camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_nouveau_bl', to='camions.camion')),
                ('nouveau_chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_nouveau_bl', to='chauffeurs.chauffeur')),
                ('nouvelle_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine_bl', to='operations.operation')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_nouveau_bl_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de nouveau BL',
                'verbose_name_plural': 'Demandes de nouveau BL',
                'ordering': ['-created_at'],
            },
        ),
    ]
