# Generated by Django 6.0.3 on 2026-05-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_villeperequation_and_more'),
        ('operations', '0016_alter_historiqueaffectationoperation_ancien_etat_bon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date_confirmation_livraison_client',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='livraison_confirmee_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='observation_confirmation_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='tarif_reference_perequation',
            field=models.DecimalField(decimal_places=2, default=550, max_digits=12),
        ),
        migrations.AddField(
            model_name='operation',
            name='ville_perequation_sgp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_sgp', to='clients.villeperequation'),
        ),
    ]
