# Generated by Django 6.0.3 on 2026-03-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('capacite', models.IntegerField()),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('mission', 'En mission'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
            ],
        ),
    ]
