# Generated by Django 6.0.3 on 2026-04-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='camion',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camion',
            name='type_camion',
            field=models.CharField(choices=[('tracteur', 'Tracteur'), ('citerne', 'Citerne')], default='tracteur', max_length=20),
        ),
        migrations.AddField(
            model_name='camion',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camions', to='camions.transporteur'),
        ),
    ]
