# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camions", "0002_transporteur_camion_marque_camion_type_camion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camion",
            old_name="immatriculation",
            new_name="numero_tracteur",
        ),
        migrations.AddField(
            model_name="camion",
            name="numero_citerne",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
