# Generated by Django 6.0.3 on 2026-04-13 16:50

from django.db import migrations, models


def forwards_map_type(apps, schema_editor):
    Camion = apps.get_model("camions", "Camion")
    Camion.objects.filter(type_camion__in=["tracteur", "citerne"]).update(
        type_camion="tracteur_citerne"
    )


def backwards_map_type(apps, schema_editor):
    Camion = apps.get_model("camions", "Camion")
    Camion.objects.filter(type_camion="tracteur_citerne").update(type_camion="tracteur")


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0003_rename_immatriculation_and_add_numero_citerne'),
    ]

    operations = [
        migrations.RunPython(forwards_map_type, backwards_map_type),
        migrations.AlterField(
            model_name='camion',
            name='type_camion',
            field=models.CharField(choices=[('tracteur_citerne', 'Tracteur + citerne'), ('camion_citerne_benne', 'Camion citerne benne')], default='tracteur_citerne', max_length=30),
        ),
    ]
