# Generated by Django 6.0.3 on 2026-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0006_alter_camion_etat_au_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='annee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='carburant',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='camion',
            name='chassis',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='camion',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='imsi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camion',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='modele',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='camion',
            name='numero_balise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camion',
            name='numero_sim',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
