# Generated by Django 6.0.3 on 2026-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0007_camion_annee_camion_carburant_camion_chassis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='code_camion',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
