# Generated by Django 6.0.3 on 2026-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0008_camion_code_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='est_affrete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
